### ISSUE TITLE
The upload.env file can't be loaded when adding the uploader.exe to the system environment variables on Windows

### ISSUE THREAD

**Issue by welovfree** [joseavilasg09/teldrive-upload#2]
The upload.env file is not loaded when the executable file (uploader.exe) is added to the system environment variables on Windows.

The same thing happens if I call uploader.exe using the relative path from another folder. So, I have to call uploader.exe from the folder it is stored in, otherwise the upload.env file will not load even though it is available in the same folder.

Using the the system environment variables:
> panic: open upload.env: The system cannot find the file specified.
> 
> goroutine 1 [running]:
> uploader/config.InitConfig()
>         uploader/config/config.go:28 +0x99
> main.main()
>         uploader/main.go:40 +0x1a6

Using the relative path:

> PS G:\Downloads\IDM\Compressed> C:\Users\justme\Desktop\Misc\teldrive-uploads\uploader.exe -path ".\Anthony Bulger - Assimil French with Ease (Book + Audio)-Assimil (2016).rar" -dest /
> panic: open upload.env: The system cannot find the file specified.
> 
> goroutine 1 [running]:
> uploader/config.InitConfig()
>         uploader/config/config.go:28 +0x99
> main.main()
>         uploader/main.go:40 +0x1a6

**Comment by joseavilasg** [comment]
@welovfree Fixed. Just make sure to place the `.env` file in the same directory as the `.exe` file.
